# docker-compose.yml

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: http://0.0.0.0:8000 # URL for the BE service
    ports:
      - "3000:3000"

