services:
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: /api  # proxy handles it
    container_name: frontend
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "3000:80"  # Expose everything on localhost:3000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
